import { login, getAuth, changePassword, logout } from './auth';
import { addNewAdmin, adminDetail, updateAdmin, getSuperAdminUser, resetPasswordAdmin } from './SuperAdmin';

import {
  getUser,
  resetPassword,
  exportOvertimeStaff,
  overTimeStaffs,
  getStaff,
  addNewStaff,
  deleteStaff,
  editStaff,
  staffDetail,
  deleteStaffImageAdmin,
  getStaffImagesAdmin,
  overtimeRequestAdmin,
  overtimeRequestAdminDetail,
  uploadStaffImage,
  voidOvertimeRequests,
} from './admin';

import { getHolidayRequester, getOwnStaff, getStaffGeneral } from './staff';
import { getAllDepartments, getManagedDepartments, getManagedAdminDepartment } from './departments';
import { HolidayDetail, addNewHoliday, deleteHoliday, holidayList, updateHoliday } from './holiday';
import { register, updateUser, userDetail } from './users';
import {
  approveOvertimeRequest,
  overtimeRequest,
  overtimeRequestDetail,
  overtimeShifts,
  rejectOvertimeRequest,
  submitOvertimeRequest,
} from './overtime';

export {
  login,
  getAuth,
  changePassword,
  getStaff,
  logout,
  getAllDepartments as getDepartment,
  HolidayDetail,
  addNewHoliday,
  deleteHoliday,
  holidayList,
  getUser,
  updateHoliday,
  addNewStaff,
  deleteStaff,
  editStaff,
  staffDetail,
  register,
  resetPassword,
  updateUser,
  userDetail,
  exportOvertimeStaff,
  overTimeStaffs,
  deleteStaffImageAdmin,
  getStaffImagesAdmin,
  overtimeRequestAdmin,
  overtimeRequestAdminDetail,
  uploadStaffImage,
  voidOvertimeRequests,
  getHolidayRequester,
  getOwnStaff,
  getStaffGeneral,
  getManagedDepartments as getDepartmentList,
  approveOvertimeRequest,
  overtimeRequest,
  overtimeRequestDetail,
  overtimeShifts,
  rejectOvertimeRequest,
  submitOvertimeRequest,
  addNewAdmin,
  adminDetail,
  updateAdmin,
  getSuperAdminUser,
  resetPasswordAdmin,
  getManagedAdminDepartment,
};
